[package]
name = "aio"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true
api.path = "../api"
db.path = "../db"
feed_loader.path = "../feed_loader"
