services:
  db:
    container_name: rss_db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
